/**
 * Best-guess CSS selector for an element discovered in the snapshot.
 *
 * Why: the experiment builder + edge proxy both need a real browser-runnable
 * CSS selector to apply a `VariantModification`. The audit pipeline only
 * tracks elements via a stable internal `ref` hash, which is useless to the
 * browser. Storing a computed selector alongside the hash lets the builder
 * pre-fill the field and the synthetic Lighthouse generator drop its
 * hardcoded selector convention.
 *
 * The stability ladder, most → least stable. Rungs 1–4 emit a durable
 * selector; if none apply we fall to rung 5, a positional path, rather than
 * `null` — an empty selector silently blocks the experiment builder and the
 * AI Variant Advisor (which targets only elements that carry a selector), so
 * on sites without test/id/name/aria anchors they'd produce nothing at all.
 * The positional selector is fragile by nature (`selectorStability()` tiers
 * it `fragile`, and the builder UI sorts it last), but a fragile selector the
 * PM can review beats no selector.
 *
 *   1. `[data-testid="..."]`, `data-test`, `data-qa`, `data-cy` — explicit
 *      test selectors, designed for stability across releases.
 *   2. `#id` — only when the id looks human-authored, not framework-emitted
 *      (`:r0:`, long hex runs, etc.).
 *   3. `tag[name="..."]` — useful for form fields and named buttons.
 *   4. `[role="..."][aria-label="..."]` — semantic + accessible-label pair.
 *   5. positional `tag:nth-of-type(k)` path — anchored on the nearest
 *      stable-selector ancestor (or `body`), capped in depth.
 *
 * All emitted values are restricted to safe character classes so we never
 * need to do general CSS-escaping. If a value contains characters we can't
 * safely embed in a quoted attribute selector, we skip that rung.
 */

import type { HTMLElement } from 'node-html-parser';

const TESTID_ATTRS = ['data-testid', 'data-test', 'data-qa', 'data-cy'] as const;
/** Restrictive on purpose — covers ~all real-world testid / name conventions. */
const SAFE_TOKEN = /^[A-Za-z0-9_-]{1,80}$/;
/** Quoted-attribute value: anything without quotes, backslashes, or newlines. */
const SAFE_QUOTED = /^[^"\\\n]{1,80}$/;
/** Reasonable human-authored id shape (starts alpha, kebab-or-snake-ish). */
const HUMAN_ID = /^[A-Za-z][A-Za-z0-9_-]{1,40}$/;

function looksAutoGenerated(id: string): boolean {
  // React 18+ useId output: `:r0:`, `:r1a:`, etc.
  if (/^:r[0-9a-z]+:?$/i.test(id)) return true;
  // Long uninterrupted hex runs (radix-ui, emotion, framework hashing).
  if (/[a-f0-9]{8,}/i.test(id) && !/[a-z]{4,}/i.test(id)) return true;
  return false;
}

/** Rungs 1–4: a durable selector, or null if no stable anchor exists. */
export function stableSelector(el: HTMLElement, tag: string): string | null {
  // 1. Explicit test selectors.
  for (const attr of TESTID_ATTRS) {
    const v = el.getAttribute(attr);
    if (v && SAFE_TOKEN.test(v)) return `[${attr}="${v}"]`;
  }
  // 2. Human-authored id.
  const id = el.getAttribute('id');
  if (id && HUMAN_ID.test(id) && !looksAutoGenerated(id)) {
    return `#${id}`;
  }
  // 3. `name` attribute (form fields, named buttons).
  const name = el.getAttribute('name');
  if (name && SAFE_TOKEN.test(name)) return `${tag}[name="${name}"]`;
  // 4. role + aria-label.
  const role = el.getAttribute('role');
  const ariaLabel = el.getAttribute('aria-label');
  if (role && ariaLabel && SAFE_TOKEN.test(role) && SAFE_QUOTED.test(ariaLabel)) {
    return `[role="${role}"][aria-label="${ariaLabel}"]`;
  }
  return null;
}

function parentOf(el: HTMLElement): HTMLElement | null {
  return (el as unknown as { parentNode: HTMLElement | null }).parentNode ?? null;
}

function tagOf(el: HTMLElement | null | undefined): string {
  return (el?.tagName ?? '').toLowerCase();
}

/** 1-based position of `el` among its parent's same-tag element children. */
function nthOfType(parent: HTMLElement | null, el: HTMLElement, tag: string): number {
  if (!parent) return 0;
  const kids = (parent as unknown as { childNodes: Array<{ nodeType: number; tagName?: string }> })
    .childNodes;
  const sameTag = kids.filter((n) => n.nodeType === 1 && (n.tagName ?? '').toLowerCase() === tag);
  const i = sameTag.indexOf(el as unknown as { nodeType: number; tagName?: string });
  return i >= 0 ? i + 1 : 0;
}

/**
 * Rung 5: a positional child-combinator path. Walks up to 6 ancestors,
 * stopping early at the first ancestor that has a stable selector (so the
 * path is anchored, e.g. `#main > section:nth-of-type(2) > a:nth-of-type(1)`)
 * or at `body`. Always returns a non-empty, browser-runnable selector.
 */
function positionalSelector(el: HTMLElement, tag: string): string {
  const segments: string[] = [];
  let cur: HTMLElement | null = el;
  let curTag = tag;
  for (let depth = 0; depth < 6 && cur && curTag; depth++) {
    const parent = parentOf(cur);
    const idx = nthOfType(parent, cur, curTag);
    segments.unshift(idx >= 1 ? `${curTag}:nth-of-type(${idx})` : curTag);
    if (!parent) break;
    const parentTag = tagOf(parent);
    if (!parentTag || parentTag === 'html') break;
    if (parentTag === 'body') {
      segments.unshift('body');
      break;
    }
    const anchor = stableSelector(parent, parentTag);
    if (anchor) {
      segments.unshift(anchor);
      break;
    }
    cur = parent;
    curTag = parentTag;
  }
  return segments.length ? segments.join(' > ') : tag;
}

export function computeCssSelector(el: HTMLElement, tag: string): string {
  return stableSelector(el, tag) ?? positionalSelector(el, tag);
}
