/**
 * Best-guess CSS selector for an element discovered in the snapshot.
 *
 * Why: the experiment builder + edge proxy both need a real browser-runnable
 * CSS selector to apply a `VariantModification`. The audit pipeline only
 * tracks elements via a stable internal `ref` hash, which is useless to the
 * browser. Storing a computed selector alongside the hash lets the builder
 * pre-fill the field and the synthetic Lighthouse generator drop its
 * hardcoded selector convention.
 *
 * The stability ladder, most → least stable. We bail to `null` rather than
 * emit a fragile class-chain selector — better an empty builder field than
 * one that silently no-ops on the next CSS refactor.
 *
 *   1. `[data-testid="..."]`, `data-test`, `data-qa`, `data-cy` — explicit
 *      test selectors, designed for stability across releases.
 *   2. `#id` — only when the id looks human-authored, not framework-emitted
 *      (`:r0:`, long hex runs, etc.).
 *   3. `tag[name="..."]` — useful for form fields and named buttons.
 *   4. `[role="..."][aria-label="..."]` — semantic + accessible-label pair.
 *
 * All emitted values are restricted to safe character classes so we never
 * need to do general CSS-escaping. If a value contains characters we can't
 * safely embed in a quoted attribute selector, we skip that rung.
 */

import type { HTMLElement } from 'node-html-parser';

const TESTID_ATTRS = ['data-testid', 'data-test', 'data-qa', 'data-cy'] as const;
/** Restrictive on purpose — covers ~all real-world testid / name conventions. */
const SAFE_TOKEN = /^[A-Za-z0-9_-]{1,80}$/;
/** Quoted-attribute value: anything without quotes, backslashes, or newlines. */
const SAFE_QUOTED = /^[^"\\\n]{1,80}$/;
/** Reasonable human-authored id shape (starts alpha, kebab-or-snake-ish). */
const HUMAN_ID = /^[A-Za-z][A-Za-z0-9_-]{1,40}$/;

function looksAutoGenerated(id: string): boolean {
  // React 18+ useId output: `:r0:`, `:r1a:`, etc.
  if (/^:r[0-9a-z]+:?$/i.test(id)) return true;
  // Long uninterrupted hex runs (radix-ui, emotion, framework hashing).
  if (/[a-f0-9]{8,}/i.test(id) && !/[a-z]{4,}/i.test(id)) return true;
  return false;
}

export function computeCssSelector(el: HTMLElement, tag: string): string | null {
  // 1. Explicit test selectors.
  for (const attr of TESTID_ATTRS) {
    const v = el.getAttribute(attr);
    if (v && SAFE_TOKEN.test(v)) return `[${attr}="${v}"]`;
  }
  // 2. Human-authored id.
  const id = el.getAttribute('id');
  if (id && HUMAN_ID.test(id) && !looksAutoGenerated(id)) {
    return `#${id}`;
  }
  // 3. `name` attribute (form fields, named buttons).
  const name = el.getAttribute('name');
  if (name && SAFE_TOKEN.test(name)) return `${tag}[name="${name}"]`;
  // 4. role + aria-label.
  const role = el.getAttribute('role');
  const ariaLabel = el.getAttribute('aria-label');
  if (role && ariaLabel && SAFE_TOKEN.test(role) && SAFE_QUOTED.test(ariaLabel)) {
    return `[role="${role}"][aria-label="${ariaLabel}"]`;
  }
  return null;
}
